os: linux
dist: focal
group: edge

language: python

python:
  - "3.9"
  - "3.8"

install: pip install tox-travis

script: tox

deploy:
  provider: pypi
  username: jacobneiltaylor
  distributions: "sdist bdist_wheel"
  skip_existing: true
  edge: true
  on:
    branch: master
    python: "3.9"
